BusBunching/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bus.urls')),
    path('admin/', admin.site.urls),
]

bus/urls.py
from django.urls import path
from .views import *
app_name = 'bus'

urlpatterns = [
    path('', home, name='home'),
    path('reset', reset, name='reset'),
    path('time_sys', sys_time, name='sys_time'),
    path('bus-schedule', schedule, name='schedule'),
    path('bus-schedule-real', realSchedule, name='real-schedule'),
    path('bus-test/<bus>', bus_test, name='bus-test'),
    path('stop-test/<stop>', stop_test, name='stop-test'),
    path('bus', bus, name='bus'),
    path('stop', stop, name='stop'),
    path('update<busstop>', update, name='update'),
    path('img', image, name='image'),
    path('jam', jam, name='jam'),
]

bus/models.py
from django.db import models
from django.urls import reverse


class State(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=30)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    def __str__(self):
        return self.name


class Route(models.Model):
    name = models.CharField(max_length=30)
    distance = models.IntegerField(default=0)
    time = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Stop(models.Model):
    name = models.CharField(max_length=30)
    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    distance = models.IntegerField(default=0)
    time = models.IntegerField(default=0)
    next = models.CharField(max_length=30)
    prev = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Bus(models.Model):
    name = models.CharField(max_length=30)
    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    next = models.CharField(max_length=30)
    prev = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class BusStop(models.Model):
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE)
    stop = models.ForeignKey(Stop, on_delete=models.CASCADE)
    route = models.ForeignKey(Route, on_delete=models.CASCADE, null=True)
    arrival = models.TimeField()
    departure = models.TimeField()

    def __str__(self):
        return str(self.bus) + "--" + str(self.stop)


class BusSchedule(models.Model):
    busstop = models.ForeignKey(BusStop, on_delete=models.CASCADE)
    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    arrival = models.TimeField()
    departure = models.TimeField()
    status = models.CharField(max_length=50, default='NOT STARTED FROM TERMINAL')

    def __str__(self):
        return str(self.busstop) + ' | ' + str(self.arrival) + ' | ' + str(self.departure) +  ' | ' + self.status

    def update(self):
        return reverse('bus:update', args=[self.busstop])


class BusStopReal(models.Model):
    date = models.DateField()
    busstop = models.ForeignKey(BusStop, on_delete=models.CASCADE, null=True)
    arrival = models.TimeField()
    departure = models.TimeField()

    def __str__(self):
        return str(self.date)+'---'+str(self.busstop.bus) + "---" + str(self.busstop.stop)

bus/views.py
from django.shortcuts import render, HttpResponse,redirect
# from django.http import HttpResponse as ht
import datetime
from .models import *
from .function import update_fun, coordinates

from io import BytesIO
import base64
import matplotlib.pyplot as plt
import numpy as np



def reset(request):
    request.session.flush()
    bus = BusStop.objects.all()
    for b in bus:
        t = BusSchedule.objects.get(busstop=b)
        t.arrival = b.arrival
        t.departure = b.departure
        t.status = "NOT STARTED FROM TERMINAL"
        t.save()
    return redirect('/')

def home(request):
    return render(request, 'index.html')


def sys_time(request):
    if 'time' in request.POST:
        time = request.POST['time']
    else:
        time = request.session['time']
    t = datetime.time(int(time[:2]), int(time[3:]))
    request.session['time'] = time
    blank = datetime.time(00, 00)
    route = Route.objects.get(name='Route 1')
    bus = BusSchedule.objects.filter(route=route)
    for b in bus:

        if b.departure < t and not (b.departure == blank):
            b.status = 'Departed From ' + b.busstop.stop.name
            b.save()
            try:
                real = BusStopReal.objects.get(busstop=b.busstop, date=datetime.date.today())
                if b.departure == real.departure:
                    pass
                else:
                    real.arrival = b.arrival
                    real.departure = b.departure
                    real.save()
            except:
                real = BusStopReal(date=datetime.date.today(), busstop=b.busstop, arrival=b.arrival,
                                   departure=b.departure)
                real.save()
        elif b.departure == t :
            b.status = 'DEPARTING FROM ' + b.busstop.stop.name
            b.save()
            try:
                real = BusStopReal.objects.get(busstop=b.busstop, date=datetime.date.today())
                if b.departure == real.departure:
                    pass
                else:
                    real.arrival = b.arrival
                    real.departure = b.departure
                    real.save()
            except:
                real = BusStopReal(date=datetime.date.today(), busstop=b.busstop, arrival=b.arrival,
                                   departure=b.departure)
                real.save()
        else:
            if b.arrival == blank and b.departure>t:
                b.status = 'NOT STARTED FROM TERMINAL'
                b.save()
            else:
                ti = b.arrival
                h = ti.hour - t.hour
                min = ti.minute - t.minute
                min += h*60
                if min < 0:
                    b.status = 'END OF JOURNEY'
                elif min == 0:
                    b.status = 'AT STOP '+b.busstop.stop.name
                else:
                    b.status = str(min) + ' MINs TO STOP ' + b.busstop.stop.name
                b.save()
    return render(request, 'schedule-real.html', {'bus':bus})


def bus_test(request, bus):

    bus_name = Bus.objects.get(name=bus)
    bus_stop = BusStop.objects.filter(bus=bus_name)
    bus_real_list = []
    for bs in bus_stop:
        bus_real = BusSchedule.objects.get(busstop=bs)
        bus_real_list.append(bus_real)
    return render(request, 'schedule-real.html', {'bus': bus_real_list})


def stop_test(request, stop):

    stop_name = Stop.objects.get(name=stop)
    bus_stop = BusStop.objects.filter(stop=stop_name)
    stop_real_list = []
    for bs in bus_stop:
        stop_real = BusSchedule.objects.get(busstop=bs)
        stop_real_list.append(stop_real)
    return render(request, 'schedule-real.html', {'bus': stop_real_list})


def schedule(request):
    route = Route.objects.get(name='Route 1')
    sch = BusStop.objects.filter(route=route)
    context = {
        'schedule': sch,
    }
    template = 'schedule.html'
    return render(request, template, context)


def realSchedule(request):
    route = Route.objects.get(name='Route 1')
    sch = BusSchedule.objects.filter(route=route)
    context = {
        'bus': sch,
    }
    template = 'schedule-real.html'
    return render(request, template, context)

def bus(request):
    route = Route.objects.get(name='Route 1')
    bus_list = Bus.objects.filter(route=route)
    template = 'bus.html'
    context = {
        'list': bus_list,
        'name': 'bus'
    }
    return render(request, template, context)


def stop(request):
    route = Route.objects.get(name='Route 1')
    stop_list = Stop.objects.filter(route=route)
    template = 'bus.html'
    context = {
        'list': stop_list,
        'name': 'stop',
    }
    return render(request, template, context)





def update(request, busstop):
    bus = busstop.split('--')[0]
    stop = busstop.split('--')[1]
    try:
        bus = Bus.objects.get(name=bus)
        stop = Stop.objects.get(name=stop)
    except:
        return HttpResponse('ERROR')
    
    if request.method == 'GET':
        route = Route.objects.get(name='Route 1')
        bus_stop = BusStop.objects.get(route=route, bus=bus, stop=stop)
        sch = BusSchedule.objects.get(busstop=bus_stop)
        context = {
            'bus' : bus,
            'stop' : stop,
            'arrival' : sch.arrival,
            'departure' : sch.departure,
        }
        return render(request, 'update.html', context=context)
    else:
        min = int(request.POST['min'])
        if min < 0:
            #arrival time will be changed departure will remain same
            route = Route.objects.get(name='Route 1')
            bus_stop = BusStop.objects.get(route=route, bus=bus, stop=stop)
            real = BusSchedule.objects.get(busstop=bus_stop)
            time = (datetime.datetime.combine(datetime.date(1, 1, 1), real.arrival) - datetime.timedelta(minutes=-min)).time()
            real.arrival = time
            real.save()
            return sys_time(request)
        else:
            route = Route.objects.get(name='Route 1')
            bus_stop = BusStop.objects.get(route=route, bus=bus, stop=stop)
            update_fun(bus_stop, min)
            return sys_time(request)

def image(request):
    crd = coordinates(request.session['time'])
    fig = plt.figure()
    ax = fig.add_subplot(111)
    print(crd['x1'],crd['y1'])
    print(crd['x2'],crd['y2'])
    ax.plot(crd['x1'], crd['y1'], color='lightblue', label='Original')
    ax.plot(crd['x2'], crd['y2'], color='darkgreen', label='Real-Time')
    ax.legend()
    pos = [i+1 for i in range(len(crd['ylable']))]
    ax.set_yticks(pos)
    ax.set_yticklabels(crd['ylable'])
    ax.set_xticklabels(crd['xlable'])
    ax.set_xticks(crd['x1'])
    ax.set_xlabel('Buses')
    ax.set_ylabel('Stops')
    ax.set_title('BUS STOP')

    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    image_png = buffer.getvalue()
    buffer.close()

    graphic = base64.b64encode(image_png)
    graphic = graphic.decode('utf-8')

    return render(request, 'graphic.html',{'graphic':graphic})

def jam(request):
    time = int(request.POST['jam'])
    start = datetime.time(int(request.session['time'][:2]), int(request.session['time'][3:]))
    end = (datetime.datetime.combine(datetime.date(1, 1, 1), start) + datetime.timedelta(minutes=time)).time()
    route = Route.objects.get(name="Route 1")
    stops = Stop.objects.filter(route=route)
    buses = Bus.objects.filter(route=route)
    for stop in stops:
        for bus in buses:
            busstop = BusStop.objects.get(bus=bus, stop=stop, route=route)
            busschedule = BusSchedule.objects.get(busstop=busstop)
            # print(busschedule.departure, start)
            if  busschedule.departure>=start or busschedule.departure == datetime.time(00,00):
                # next_stop = stop.next   
                # next_stop = Stop.objects.get(name=next_stop, route=route)
                # next_bus_stop = BusStop.objects.get(bus=bus, stop=next_stop, route=route)
                if busschedule.arrival>=start and busschedule.arrival != datetime.time(0,0):
                    busschedule.arrival = (datetime.datetime.combine(datetime.date(1, 1, 1), busschedule.arrival) + datetime.timedelta(minutes=time)).time()
                    busschedule.save()
                if busschedule.departure != datetime.time(00,00):
                    busschedule.departure = (datetime.datetime.combine(datetime.date(1, 1, 1), busschedule.departure) + datetime.timedelta(minutes=time)).time()
                    busschedule.save()
    for bus in buses:
        for s in stops:
            busstoptemp = BusStop.objects.get(route=route, bus=bus, stop=s)
            real = BusSchedule.objects.get(busstop=busstoptemp)
            if real.busstop.bus.next == 'NA':
                pass
            else:
                next_bus = Bus.objects.get(name=real.busstop.bus.next, route=route)
                next_busstop = BusStop.objects.get(bus=next_bus, stop=s, route=route)
                next_real = BusSchedule.objects.get(busstop=next_busstop)
                h = real.arrival.hour - next_real.arrival.hour
                m = real.arrival.minute - next_real.arrival.minute
                diff = h*60 + m
                if diff > 0:
                    if diff < 5:
                        real.departure = (datetime.datetime.combine(datetime.date(1, 1, 1), real.departure) + datetime.timedelta(minutes=5-diff)).time()
                        real.save()
                else:
                    update_fun(next_busstop,(10+diff))
    
    return sys_time(request)
                

bus/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}

        {% endblock title %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item"><a href="{% url 'bus:home' %}" class="nav-link">Bus Bunching</a></li>
            <li class="nav-item">
                <form action="{% url 'bus:sys_time' %}" method="post" class="form-inline">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="text" name="time" id="time"
                        value="{{request.session.time}}"><br />
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </li>
            <li class="nav-item "><a class="btn btn-danger" href="{% url 'bus:reset' %}">Reset</a></li>
            {% if request.session.time %}
            <li class="nav-item "><a class="btn btn-primary" href="{% url 'bus:image' %}">Graph</a></li>
            {% endif %}

        </ul>
    </nav>

    <h1 style="padding: 10px;">{% block heading %}{% endblock heading %}</h1>
    <div style="width:100%;height:5px;background-color: red;"></div>
    {% block body %}
    {% endblock body %}
    <div class="jumbotron" style="margin-bottom:0">
        <ul class="list-group list-group-flush">
            {% if request.session.time %}
            <li class="list-group-item">
                <form action="{% url 'bus:jam' %}" method="post" class="form-inline">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="text" name="jam" id="jam" placeholder="Enter jam duration">
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </li>
            {% endif %}
            <li class="list-group-item"><a href="{% url 'bus:schedule' %}">Bus ScheduleOriginal</a></li>
            <li class="list-group-item"><a href="{% url 'bus:real-schedule' %}">Bus Schedule Real-Time</a></li>
            <li class="list-group-item"><a href="{% url 'bus:bus' %}">Buses</a></li>
            <li class="list-group-item"><a href="{% url 'bus:stop' %}">Stops</a></li>
        </ul>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

bus/templates/bus.html
{% extends 'base.html' %}
{% block title %}
{{name}}
{% endblock title %}
{% block heading %}
{{name|title}}
{% endblock heading %}
{% block body %}

<ul class="list-group list-group-flush">
    {% for b in list %}
    <li class="list-group-item">
        <a href="/{{ name }}-test/{{ b.name }}">{{b}}</a>
    </li>
    {% endfor %}
</ul>
{% endblock body %}
    

bus/templates/graphic.html
{% extends 'base.html' %}
{% block title %}
Grpah
{% endblock title %}
{% block heading %}
Graph
{% endblock heading %}
{% block body %}
<img src="data:image/png;base64,{{ graphic|safe }}">
{% endblock body %}

bus/templates/index.html
{% extends 'base.html' %}
{% block title %}HOME{% endblock title %}
{% block heading %}
HOME
{% endblock heading %}
{% block body %}
<ul class="list-group list-group-flush">
    <li class="list-group-item"><a href="{% url 'bus:schedule' %}">Bus ScheduleOriginal</a></li>
    <li class="list-group-item"><a href="{% url 'bus:real-schedule' %}">Bus Schedule Real-Time</a></li>
    <li class="list-group-item"><a href="{% url 'bus:bus' %}">Buses</a></li>
    <li class="list-group-item"><a href="{% url 'bus:stop' %}">Stops</a></li>
    <li class="list-group-item"><a href="{% url 'bus:reset' %}">Reset</a></li>
</ul>
{% endblock body %}

bus/templates/schedule-real.html
{% extends 'base.html' %}
{% block title %}
Schedule
{% endblock title %}
{% block heading %}
Schedule
{% endblock heading %}
{% block body %}
<table class="table">
    <thead>
        <tr>
            <th>Bus</th>
            <th>Stop</th>
            <th>Arrival Time</th>
            <th>Departure Time</th>
            <th>Status</th>
            <th>Update</th>
        </tr>
    </thead>
    <tbody>
        {% for b in bus %}
        <tr>
            <td>{{ b.busstop.bus }}</td>
            <td>{{ b.busstop.stop }}</td>
            <td>{{ b.arrival }}</td>
            <td>{{ b.departure }}</td>
            <td>{{ b.status }}</td>
            <td>
                {% if 'MINs' in b.status %}
                <a class="btn btn-info" href="{{ b.update }}">update</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>

</table>
{% endblock body %}

bus/templates/schedule.html
{% extends 'base.html' %}
{% block title %}
Schedule
{% endblock title %}
{% block heading %}
Schedule
{% endblock heading %}
{% block body %}
<table class="table">
    <thead>
        <tr>
            <th>Bus</th>
            <th>Stop</th>
            <th>Arrival Time</th>
            <th>Departure Time</th>
        </tr>
    </thead>
    <tbody>
        {% for s in schedule %}
        <tr>
            <td>{{ s.bus }}</td>
            <td>{{ s.stop }}</td>
            <td>{{ s.arrival }}</td>
            <td>{{ s.departure }}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock body %}

bus/templates/update.html
{% extends 'base.html' %}
{% block title %}
{{bus}}--{{stop}}--update
{% endblock title %}
{% block heading %}
Update {{bus}} {{stop}}
{% endblock heading %}
{% block body %}
<ul class="list-group list-group-flush">
    <li class="list-group-item">BUS :: {{bus}}</li>
    <li class="list-group-item">STOP :: {{stop}}</li>
    <li class="list-group-item">ARRIVAL TIME :: {{arrival}}</li>
    <li class="list-group-item">DEPARTURE TIME :: {{departure}}</li>
</ul>
<h4>Enter minutes to update</h4>
<form class="form-inline container" action="" method="POST">
    {% csrf_token %}
    <input class="form-control" type="number" name="min" id="">
    <button class="btn btn-success" type="submit">submit</button>
</form>
{% endblock body %}